### ISSUE TITLE
Enhancement: Filter design improvement

### ISSUE THREAD

**Issue by hongsam14** [enki-polvo/polvo#6]
According to #4  requested changed issue, It seems reasonable that filter syntax design should be improved.

## Current Behavior

``` yaml
version: 1.0
allow:
  "filter_test":
    "eventname|contains":
      - "bashReadline"
      - "process"
    "Commandline|contains":
      - "ls"
      - "cat"
deny:
  "!filter_NOT":
    "eventname|startswith": "process"

```

## Expected Behavior

``` yaml
version: 1.0
deny:
  "filter_test":
    "condition":
      "eventname|contains":
        - "bashReadline"
    "exception":
      "eventname|contains":
        - "bashReadline"
        - "process"
      "Commandline|contains":
        - "ls"
        - "cat"
   
```
Since the sensor's primary function is to collect logs, it is reasonable for the filter to have a structure that has a single role of denying log collection.
However, we need an exception clause so that we can write exception cases.
